services:
  db:
    image: postgres:latest
    container_name: pl-pgsql-practice-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER is not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is not set}
      POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB is not set}
    ports:
      - "${POSTGRES_PORT:?POSTGRES_PORT is not set}:5432"
    volumes:
      - db-data:/var/lib/postgresql

volumes:
  db-data:
